# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-HtmlTidy
version:      0.50
version_from: lib/CGI/Application/Plugin/HtmlTidy.pm
installdirs:  site
requires:
    CGI::Application:              4.01
    HTML::Tidy:                    1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
