--- #YAML:1.0
name:                CGI-Application-Plugin-HtmlTidy
version:             1.02
abstract:            Add HTML::Tidy support to CGI::Application
license:             perl
author:              
    - Rhesa Rozendaal <rhesa@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI::Application:              4.01
    HTML::Tidy:                    1.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
